var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(utility)/knowledge/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ualo6_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0y0g4zq.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_1061qcx._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(utility)_knowledge_page_actions_0v4d_fh.js")
R.m(807278)
module.exports=R.m(807278).exports
