var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/admin/users/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vbcp_c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0g0i-~f.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(admin)_layout_tsx_0e6mepu._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(admin)_admin_users_page_actions_0qsz4q4.js")
R.m(948144)
module.exports=R.m(948144).exports
