var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(workspace)/partners/[partnerId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kjgbly._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_13409v9.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_12u~99i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(workspace)_partners_[partnerId]_page_actions_07k3rsh.js")
R.m(649813)
module.exports=R.m(649813).exports
