var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(workspace)/co-writer/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ehj9cy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0mo-wwc.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_12u~99i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(workspace)_co-writer_page_actions_1286.t0.js")
R.m(46470)
module.exports=R.m(46470).exports
