// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/users" | "/agents" | "/book" | "/co-writer" | "/co-writer/[docId]" | "/home/[[...sessionId]]" | "/knowledge" | "/login" | "/memory" | "/memory/graph" | "/memory/l1" | "/memory/l2" | "/memory/l2/[surface]" | "/memory/l3" | "/memory/l3/[slot]" | "/memory/resolve" | "/notebook" | "/partners" | "/partners/[partnerId]" | "/partners/new" | "/playground" | "/profile" | "/register" | "/settings" | "/settings/agents" | "/settings/agents/claude-code" | "/settings/agents/codex" | "/settings/agents/gemini" | "/settings/agents/kimi" | "/settings/agents/mimo" | "/settings/agents/opencode" | "/settings/appearance" | "/settings/attachments" | "/settings/capabilities" | "/settings/chat" | "/settings/document-parsing" | "/settings/embedding" | "/settings/image" | "/settings/llm" | "/settings/mcp" | "/settings/memory" | "/settings/mineru" | "/settings/models" | "/settings/network" | "/settings/search" | "/settings/status" | "/settings/stt" | "/settings/tools" | "/settings/tts" | "/settings/video" | "/space" | "/space/chat-history" | "/space/cli-apps" | "/space/learning" | "/space/mcp" | "/space/notebooks" | "/space/personas" | "/space/questions" | "/space/skills"
type PageRoutes = never
type LayoutRoutes = "/" | "/agents" | "/memory" | "/settings" | "/space"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin/users": {}
  "/agents": {}
  "/book": {}
  "/co-writer": {}
  "/co-writer/[docId]": { "docId": string; }
  "/home/[[...sessionId]]": { "sessionId"?: string[]; }
  "/knowledge": {}
  "/login": {}
  "/memory": {}
  "/memory/graph": {}
  "/memory/l1": {}
  "/memory/l2": {}
  "/memory/l2/[surface]": { "surface": string; }
  "/memory/l3": {}
  "/memory/l3/[slot]": { "slot": string; }
  "/memory/resolve": {}
  "/notebook": {}
  "/partners": {}
  "/partners/[partnerId]": { "partnerId": string; }
  "/partners/new": {}
  "/playground": {}
  "/profile": {}
  "/register": {}
  "/settings": {}
  "/settings/agents": {}
  "/settings/agents/claude-code": {}
  "/settings/agents/codex": {}
  "/settings/agents/gemini": {}
  "/settings/agents/kimi": {}
  "/settings/agents/mimo": {}
  "/settings/agents/opencode": {}
  "/settings/appearance": {}
  "/settings/attachments": {}
  "/settings/capabilities": {}
  "/settings/chat": {}
  "/settings/document-parsing": {}
  "/settings/embedding": {}
  "/settings/image": {}
  "/settings/llm": {}
  "/settings/mcp": {}
  "/settings/memory": {}
  "/settings/mineru": {}
  "/settings/models": {}
  "/settings/network": {}
  "/settings/search": {}
  "/settings/status": {}
  "/settings/stt": {}
  "/settings/tools": {}
  "/settings/tts": {}
  "/settings/video": {}
  "/space": {}
  "/space/chat-history": {}
  "/space/cli-apps": {}
  "/space/learning": {}
  "/space/mcp": {}
  "/space/notebooks": {}
  "/space/personas": {}
  "/space/questions": {}
  "/space/skills": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/agents": never
  "/memory": never
  "/settings": never
  "/space": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
