// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/(utility)/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge">> = Specific
  const handler = {} as typeof import("../../app/(utility)/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/graph/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/graph">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/graph/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/l1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/l1">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/l1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/l2/[surface]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/l2/[surface]">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/l2/[surface]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/l2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/l2">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/l2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/l3/[slot]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/l3/[slot]">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/l3/[slot]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/l3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/l3">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/l3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/resolve/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory/resolve">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/resolve/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/notebook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebook">> = Specific
  const handler = {} as typeof import("../../app/(utility)/notebook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/(utility)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/claude-code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents/claude-code">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/claude-code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/codex/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents/codex">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/codex/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/gemini/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents/gemini">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/gemini/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/kimi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents/kimi">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/kimi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/mimo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents/mimo">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/mimo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/opencode/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents/opencode">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/opencode/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agents">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/appearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/appearance">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/appearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/attachments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/attachments">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/attachments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/capabilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/capabilities">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/capabilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/chat">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/document-parsing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/document-parsing">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/document-parsing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/embedding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/embedding">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/embedding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/image/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/image">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/image/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/llm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/llm">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/llm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/mcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/mcp">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/mcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/memory">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/mineru/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/mineru">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/mineru/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/models">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/network">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/search">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/status">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/stt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/stt">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/stt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/tools">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/tts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/tts">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/tts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/video">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/chat-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/chat-history">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/chat-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/cli-apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/cli-apps">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/cli-apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/learning">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/mcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/mcp">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/mcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/notebooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/notebooks">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/notebooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/personas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/personas">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/personas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/questions">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space/skills">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/co-writer/[docId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/co-writer/[docId]">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/co-writer/[docId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/co-writer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/co-writer">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/co-writer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/home/[[...sessionId]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home/[[...sessionId]]">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/home/[[...sessionId]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/partners/[partnerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/[partnerId]">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/partners/[partnerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/partners/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/new">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/partners/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/agents/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/(utility)/agents/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(utility)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/memory/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/memory">> = Specific
  const handler = {} as typeof import("../../app/(utility)/memory/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(utility)/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(utility)/space/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/space">> = Specific
  const handler = {} as typeof import("../../app/(utility)/space/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
