var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(workspace)/home/[[...sessionId]]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rlgvdx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_02xkmx-.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_12u~99i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(workspace)_home_[[___sessionId]]_page_actions_0ok-zlc.js")
R.m(776057)
module.exports=R.m(776057).exports
