var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/register/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y9~b4d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ow~wrd.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(auth)_layout_tsx_0.jbhx1._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_register_page_actions_02nrb_5.js")
R.m(911686)
module.exports=R.m(911686).exports
