var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(utility)/space/mcp/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qdzshu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~i_kmk.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_1061qcx._.js")
R.c("server/chunks/ssr/_0u9bhfz._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(utility)_space_mcp_page_actions_0ralhav.js")
R.m(636790)
module.exports=R.m(636790).exports
