var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(utility)/settings/attachments/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fv.p3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_039rfw7.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_1061qcx._.js")
R.c("server/chunks/ssr/_0c7~wvx._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(utility)_settings_attachments_page_actions_05ob_xt.js")
R.m(92531)
module.exports=R.m(92531).exports
