var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(workspace)/co-writer/[docId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10_~emy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_08.3x7..js")
R.c("server/chunks/ssr/[root-of-the-server]__01ey0yy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ell8o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_12u~99i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(workspace)_co-writer_[docId]_page_actions_0o6kek_.js")
R.m(344695)
module.exports=R.m(344695).exports
